### ISSUE TITLE
[NIBR] No comparison results within the same library

### ISSUE THREAD

**Issue by chienhsiang** [MaayanLab/enrichmentAPI#11]
Hi,

I tried the latest version of UI, metadata-api and data-api. I found that when using the drop-down menu for Signature Search, there is no result from the same library as the submitted signature. This behavior is the same for both gene-set type and rank type signatures.

There is an error in data-api log: "org.json.JSONException: JSON does not allow non-finite numbers". Is that caused by the NaN or Inf value when the signature is compared to itself?

This behavior appears after v1.3.

The full error is:
data-api_1      | org.json.JSONException: JSON does not allow non-finite numbers.
data-api_1      | 	at org.json.JSONObject.testValidity(JSONObject.java:2214)
data-api_1      | 	at org.json.JSONObject.put(JSONObject.java:1813)
data-api_1      | 	at serv.EnrichmentTemp.returnOverlapJSON(EnrichmentTemp.java:292)
data-api_1      | 	at serv.EnrichmentTemp.doPost(EnrichmentTemp.java:795)
data-api_1      | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
data-api_1      | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
data-api_1      | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
data-api_1      | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
data-api_1      | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
data-api_1      | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
data-api_1      | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
data-api_1      | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
data-api_1      | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
data-api_1      | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
data-api_1      | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
data-api_1      | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
data-api_1      | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
data-api_1      | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
data-api_1      | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
data-api_1      | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
data-api_1      | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
data-api_1      | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
data-api_1      | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
data-api_1      | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
data-api_1      | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
data-api_1      | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
data-api_1      | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
data-api_1      | 	at java.base/java.lang.Thread.run(Thread.java:834)

Thank you so much for your help!

Best,

Charles

**Comment by u8sand** [comment]
Can you confirm that you still have this? We also experienced this for a short period of time *on* v1.3.1, but not in v1.3.2. It should have been fixed by c5266171d65f790b7c4b72b63c1285ca70307593

**Comment by chienhsiang** [comment]
Hi Daniel,

v1.3.2 is working! Thank you so much!
However, the "latest" version is not working. Maybe it points to an older version?

Does the UI adjust the background automatically now?
